version: "3.8"
services:
  liferay74-tomcat-simple-1:
    image: liferay/portal:7.4.3.46-ga46
    container_name: liferay74-tomcat-simple-1
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: liferay
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://mysql8-simple:3306/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: liferay
    depends_on:
      - mysql
    networks:
      - network-liferay74-tomcat-simple
    ports:
      - 8081:8080
      - 127.0.0.1:11311:11311
    volumes:
      - volume-liferay74-simple-tomcat-data:/opt/liferay/data
      - volume-liferay74-simple-tomcat-1-work:/opt/liferay/work
  mysql:
    image: mysql:8.0.31-oracle
    container_name: mysql8-simple
    networks:
      - network-liferay74-tomcat-simple
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: liferay
      MYSQL_DATABASE: lportal
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: liferay
    volumes:
      - volume-mysql8-simple:/var/lib/mysql
networks:
  network-liferay74-tomcat-simple:
    name: network-liferay74-tomcat-simple
volumes:
  volume-liferay74-simple-tomcat-data:
  volume-liferay74-simple-tomcat-1-work:
  volume-mysql8-simple:
